version: "3.5"
services:
  postgres:
    container_name: postgres-container
    image: postgres:12-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPASSWORD=${PGPASSWORD}
    networks:
      - c-network
    ports:
      - "${EXTERNAL_PORT_POSTGRES}:${INTERNAL_PORT_POSTGRES}"
    volumes:
      - lol:/var/lib/postgresql/data
    restart: always
  adminer:
    container_name: adminer-container
    image: adminer:latest
    ports:
      - "${EXTERNAL_PORT_ADMINER}:${INTERNAL_PORT_ADMINER}"
    networks:
      - c-network
    restart: always

networks:
  c-network:
    name: containers-network
    driver: bridge


#docker compose up --build -d
#df -h /Users/mortiz-d/Library/Containers/com.docker.docker/Data/vms/0/data

volumes:
    lol : {}